// =============================================================================
// cookie-manager.js — Exports session cookies as a Netscape HTTP Cookie File
// One instance per embedded source (YouTube Music, Spotify, …) — the same code
// path serves any partitioned Electron session and any cookie domain.
// =============================================================================

import fs from 'node:fs/promises';
import path from 'node:path';
import { app } from 'electron';

export default class CookieManager {
  /**
   * @param {object} opts
   * @param {Electron.Session} opts.session — partitioned session (e.g. session.fromPartition('persist:spotify'))
   * @param {string} opts.cookieDomain — domain filter passed to session.cookies.get (e.g. '.youtube.com')
   * @param {string} opts.cookieFileName — file name within userData (e.g. 'youtube-cookies.txt')
   * @param {string[]} [opts.authCookieNames] — cookies whose presence indicates a signed-in session
   */
  constructor({ session, cookieDomain, cookieFileName, authCookieNames = [] }) {
    if (!session || !cookieDomain || !cookieFileName) {
      throw new Error('CookieManager requires { session, cookieDomain, cookieFileName }');
    }
    this.session = session;
    this.cookieDomain = cookieDomain;
    this.authCookieNames = authCookieNames;
    this.cookieFilePath = path.join(app.getPath('userData'), cookieFileName);
  }

  async _getSessionCookies() {
    return this.session.cookies.get({ domain: this.cookieDomain });
  }

  /**
   * Convert an array of Electron cookie objects to Netscape HTTP Cookie File format.
   *
   * Each line: domain \t includeSubdomains \t path \t secure \t expiry \t name \t value
   */
  _toNetscapeFormat(cookies) {
    const header = '# Netscape HTTP Cookie File\n# Generated by SetEngine\n\n';

    const lines = cookies.map((c) => {
      const domain = c.domain.startsWith('.') ? c.domain : `.${c.domain}`;
      const includeSubdomains = domain.startsWith('.') ? 'TRUE' : 'FALSE';
      const isSecure = c.secure ? 'TRUE' : 'FALSE';
      // Electron stores expirationDate as seconds since epoch (float).
      // If missing (session cookie), use 0.
      const expiry = c.expirationDate ? Math.round(c.expirationDate) : 0;
      return `${domain}\t${includeSubdomains}\t${c.path}\t${isSecure}\t${expiry}\t${c.name}\t${c.value}`;
    });

    return header + lines.join('\n') + '\n';
  }

  /**
   * Extract cookies from the session and write them to disk in Netscape format.
   * @returns {Promise<string>} — path to the written cookie file
   */
  async exportCookies() {
    const cookies = await this._getSessionCookies();
    const netscapeStr = this._toNetscapeFormat(cookies);
    await fs.writeFile(this.cookieFilePath, netscapeStr, 'utf-8');
    return this.cookieFilePath;
  }

  /**
   * True when every configured auth cookie is present in the session. With an
   * empty authCookieNames list this is a no-op that always returns true.
   */
  async isAuthenticated() {
    if (this.authCookieNames.length === 0) return true;
    const cookies = await this._getSessionCookies();
    const names = new Set(cookies.map((c) => c.name));
    return this.authCookieNames.every((n) => names.has(n));
  }

  getCookiePath() {
    return this.cookieFilePath;
  }

  async cookieFileExists() {
    try {
      await fs.access(this.cookieFilePath);
      return true;
    } catch {
      return false;
    }
  }
}
